# Generated by Django 5.2.8 on 2025-11-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['-fecha_estreno']},
        ),
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='obras/'),
        ),
    ]
