# Generated by Django 5.2.8 on 2025-11-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teatro', '0002_alter_obra_options_obra_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={},
        ),
        migrations.RemoveField(
            model_name='obra',
            name='imagen',
        ),
    ]
