# Generated by Django 5.2.8 on 2025-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatro', '0004_alter_obra_options_obra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Comedia', 'Comedia'), ('Tragedia', 'Tragedia'), ('Musical', 'Musical'), ('Thriller', 'Thriller'), ('Experimental', 'Experimental'), ('Sainete', 'Sainete'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
    ]
